"""Writes editor/art/referee.js from the drawing: python3 tools/fighter_art/export.py"""
from pathlib import Path
import referee

OUT = Path(__file__).resolve().parents[2] / "editor" / "art" / "referee.js"
RSLOT = {' ': '0', 's': '1', 'w': '2', 'k': '3'}


def main():
    lines = ["// Generated by tools/fighter_art/export.py. Edit the drawing there, then rerun it.", "",
             "// The referee, 24x32 pixels: 0 clear, 1 skin, 2 shirt, 3 black.", "export const REF_POSES = {"]
    for name, rows in referee.poses().items():
        lines.append(f"  {name}: '{''.join(RSLOT[c] for r in rows for c in r)}',")
    lines += ["};", ""]
    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines))
    print("wrote", OUT, OUT.stat().st_size, "bytes")


if __name__ == "__main__":
    main()
