"""The referee: an original character. ' ' clear, 's' skin, 'w' shirt (light), 'k' black."""

STAND = """
........kkkkkk..........
.......kssssssk.........
......kssssssssk........
.....kwssssssssswk......
.....kwskkskkssswk......
.....kskwkkwkkssk.......
.....ksskkskksssk.......
......ksssssssssk.......
......kssskkkssk........
.......kssssssk.........
........kkskkk..........
......kkkkkkkkkk........
....kkwwwkkkkwwwkk......
...kwwwwwwkkwwwwwwk.....
...kwwwwwwwwwwwwwwk.....
..kwwkwwwwwwwwwwkwwk....
..kwwkwwwwwwwwwwkwwk....
..kssk.kwwwwwwk.kssk....
..kssk.kwwwwwwk.kssk....
..kssk.kwwwwwwk.kssk....
...kk..kwwwwwwk..kk.....
.......kkkkkkkk.........
.......kkkkkkkk.........
.......kkkkkkkk.........
.......kkk..kkk.........
.......kkk..kkk.........
.......kkk..kkk.........
.......kkk..kkk.........
......kkkk..kkkk........
.....kkkkk..kkkkk.......
"""

COUNT = """
........kkkkkk.....kk...
.......kssssssk...kssk..
......kssssssssk..kssk..
.....kwssssssssswkkssk..
.....kwskkskkssswkksk...
.....kskwkkwkkssk.kssk..
.....ksskkskksssk.kssk..
......ksssssssssk.kwwk..
......kssskkkssk..kwwk..
.......kssssssk..kwwwk..
........kkskkk..kwwwk...
......kkkkkkkkkkwwwk....
....kkwwwkkkkwwwwwk.....
...kwwwwwwkkwwwwwk......
...kwwwwwwwwwwwwwk......
..kwwkwwwwwwwwwwk.......
..kwwkwwwwwwwwwwk.......
..kssk.kwwwwwwk.........
..kssk.kwwwwwwk.........
..kssk.kwwwwwwk.........
...kk..kwwwwwwk.........
.......kkkkkkkk.........
.......kkkkkkkk.........
.......kkkkkkkk.........
.......kkk..kkk.........
.......kkk..kkk.........
.......kkk..kkk.........
.......kkk..kkk.........
......kkkk..kkkk........
.....kkkkk..kkkkk.......
"""

WAVE = """
........kkkkkk..........
.......kssssssk.........
......kssssssssk........
.....kwssssssssswk......
.....kwskkskkssswk......
.....kskwkkwkkssk.......
.....ksskkskksssk.......
......ksssssssssk.......
......ksskkkkssk........
.......kssssssk.........
.kk.....kkskkk.....kk...
kssk..kkkkkkkkkk..kssk..
kwwwkkwwwkkkkwwwkkwwwk..
.kwwwwwwwwkkwwwwwwwwk...
...kwwwwwwwwwwwwwwk.....
...kwwwwwwwwwwwwwwk.....
...kwwwwwwwwwwwwwwk.....
....kwwwwwwwwwwwwk......
.....kwwwwwwwwwwk.......
.....kwwwwwwwwwwk.......
......kwwwwwwwwk........
.......kkkkkkkk.........
.......kkkkkkkk.........
.......kkkkkkkk.........
.......kkk..kkk.........
.......kkk..kkk.........
.......kkk..kkk.........
.......kkk..kkk.........
......kkkk..kkkk........
.....kkkkk..kkkkk.......
"""


def poses():
    out = {}
    for name, art in (("stand", STAND), ("count", COUNT), ("wave", WAVE)):
        rows = art.strip("\n").split("\n")
        rows += ["." * 24] * (32 - len(rows))
        assert all(len(r) == 24 for r in rows), name
        out[name] = [r.replace(".", " ") for r in rows]
    return out
