; Generated by gbstage from "My Game". Changes here are overwritten on the next build.

DEF rP1    EQU $FF00
DEF rIF    EQU $FF0F
DEF rLCDC  EQU $FF40
DEF rSCY   EQU $FF42
DEF rSCX   EQU $FF43
DEF rLY    EQU $FF44
DEF rBGP   EQU $FF47
DEF rOBP0  EQU $FF48
DEF rVBK   EQU $FF4F
DEF rHDMA1 EQU $FF51
DEF rHDMA2 EQU $FF52
DEF rHDMA3 EQU $FF53
DEF rHDMA4 EQU $FF54
DEF rHDMA5 EQU $FF55
DEF rBCPS  EQU $FF68
DEF rBCPD  EQU $FF69
DEF rOCPS  EQU $FF6A
DEF rOCPD  EQU $FF6B
DEF rIE    EQU $FFFF
DEF OAM_CURSOR EQU $FE00

DEF MAP_W EQU 20
DEF MAP_H EQU 18
DEF FADE_STEPS EQU 4
DEF FADE_FRAMES EQU 3
DEF BLINK_FRAMES EQU 4
DEF LCDC_ON EQU %10000001

; joypad bits in hPad / hPadNew (d-pad in the high nibble)
DEF PAD_A EQU 0
DEF PAD_B EQU 1
DEF PAD_START EQU 3
DEF PAD_UP EQU 6
DEF PAD_DOWN EQU 7
DEF PADF_A EQU 1 << PAD_A
DEF PADF_B EQU 1 << PAD_B
DEF PADF_START EQU 1 << PAD_START
DEF PAD_RIGHT EQU 4
DEF PAD_LEFT EQU 5
DEF PADF_UP EQU 1 << PAD_UP
DEF PADF_DOWN EQU 1 << PAD_DOWN
DEF PADF_LEFT EQU 1 << PAD_LEFT
DEF PADF_RIGHT EQU 1 << PAD_RIGHT
DEF SFX_NOTE_TOP EQU 72
DEF SFX_MENU_MOVE EQU 0
DEF SFX_MENU_CONFIRM EQU 1
DEF SFX_MENU_BACK EQU 2
DEF SFX_OPTION_CHANGE EQU 3
DEF SFX_PRESS_START EQU 4

MACRO PZ_SFX                ; play sound effect \1
    ld a, \1
    call PlaySfx
ENDM

MACRO PZ_SFX_A              ; play sound effect A
    call PlaySfx
ENDM

MACRO PZ_CLEAR_SFX          ; play the clear sound A semitones up
    ldh [hSfxTranspose], a
    ld a, SFX_CLEAR
    call PlaySfx
ENDM
DEF REPEAT_DELAY EQU 16       ; frames a direction is held before it repeats
DEF REPEAT_RATE EQU 4         ; frames between repeats after that


MACRO QUEUE_PATCH           ; apply patch routine \1 to the tiles at HL during the next VBlank
    ld a, l
    ldh [hPatchSrc], a
    ld a, h
    ldh [hPatchSrc + 1], a
    ld a, LOW(\1)
    ldh [hPatchJump + 1], a
    ld a, HIGH(\1)
    ldh [hPatchJump + 2], a
    ld a, 1
    ldh [hPatchPending], a  ; set last
ENDM

MACRO SET_UPDATE            ; run \1 every frame from now on
    ld a, LOW(\1)
    ldh [hUpdateJump + 1], a
    ld a, HIGH(\1)
    ldh [hUpdateJump + 2], a
ENDM

SECTION "Header", ROM0[$100]
    nop
    jp Start
    ds $150 - @, 0

SECTION "Stack", WRAM0
    ds 64
wStackTop:
wSavedSP: dw

SECTION "Code: Start", ROM0
Start:
    ; The boot ROM leaves A = $11 on Game Boy Color hardware, and interrupts disabled (they stay that way).
    cp $11
    ld a, 0
    jr nz, .notCGB
    inc a
.notCGB:
    ldh [hIsCGB], a
    ld sp, wStackTop
.waitVBlank:                ; the LCD may only be switched off during VBlank
    ldh a, [rLY]
    cp 144
    jr c, .waitVBlank
.waitVBlankDone:            ; labels named .waitX/.waitXDone mark idle loops for the profiler
    xor a
    ldh [rLCDC], a
    ldh [rSCY], a
    ldh [rSCX], a
    ld hl, hVars            ; clear the HRAM variables
    xor a
    ld b, hVarsEnd - hVars
.clearVars:
    ld [hl+], a
    dec b
    jr nz, .clearVars
    call SfxInit
    ld a, $C3               ; JP opcode for the update trampoline
    ldh [hUpdateJump], a
    ldh [hPatchJump], a     ; ... and for the patch trampoline
    ld a, 1                 ; VBlank wakes HALT; no interrupt handler ever runs
    ldh [rIE], a
    ld a, 0
    call LoadScene
MainLoop:
    xor a
    ldh [rIF], a
    halt                    ; sleep until VBlank
    nop                     ; HALT may run the next byte twice if VBlank arrives just before it
    ldh a, [hPalDirty]
    and a
    call nz, UploadPalettes
    ldh a, [hPatchPending]  ; a queued map patch (blink, flash, prompt)
    and a
    jr z, .noPatch
    xor a
    ldh [hPatchPending], a
    ld hl, hPatchSrc
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    call hPatchJump
.noPatch:
VBlankDone:                 ; everything that must happen during VBlank is done
    ld hl, hFrame
    inc [hl]
    ld a, $20               ; read the d-pad
    ldh [rP1], a
    ldh a, [rP1]
    ldh a, [rP1]
    cpl
    and $0F
    swap a
    ld b, a
    ld a, $10               ; read the buttons
    ldh [rP1], a
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    cpl
    and $0F
    or b
    ld b, a
    ld a, $30
    ldh [rP1], a
    ldh a, [hPad]
    xor b
    and b
    ldh [hPadNew], a        ; pressed this frame
    ld a, b
    ldh [hPad], a           ; held
    call hUpdateJump
    call SfxUpdate
    jp MainLoop

SECTION "Code: Scenes", ROM0
; Load scene A with the screen off. Tiles, map and palette map go by DMA on Game Boy Color.
LoadScene:
    ldh [hScene], a
    ldh a, [rLCDC]
    add a                   ; screen already off (at boot)? bit 7 -> carry
    jr nc, .screenOff
.waitVBlank:
    ldh a, [rLY]
    cp 144
    jr c, .waitVBlank
.waitVBlankDone:
    xor a
    ldh [rLCDC], a
.screenOff:
    ldh a, [hScene]
    add a
    add LOW(SceneLoads)
    ld l, a
    adc HIGH(SceneLoads)
    sub l
    ld h, a
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    call JumpHL
    xor a
    ldh [hPatchPending], a
    ldh [hPromptHidden], a
    ld a, FADE_STEPS        ; start fully faded; FadeIn brings the colors up
    ldh [hFadeStep], a
    ld a, FADE_FRAMES
    ldh [hTimer], a
    SET_UPDATE FadeIn
    call UploadPalettes
    ld a, LCDC_ON
    ldh [rLCDC], a
    ret

JumpHL:
    jp hl

SceneLoads:
    dw Scene0Load, Scene1Load


Scene0Load:
    ld hl, Scene0Tiles
    ld de, $9000            ; tiles 0-127
    ld c, 95
    call CopyTiles
    ld hl, Scene0Map
    call CopyMap
    ld hl, Scene0Attr
    call CopyAttr
    ret
Scene1Load:
    ld hl, Scene1Tiles
    ld de, $9000            ; tiles 0-127
    ld c, 22
    call CopyTiles
    ld hl, Scene1Map
    call CopyMap
    ld hl, Scene1Attr
    call CopyAttr
    ret

; Copy C tiles (1-128) from HL to DE.
CopyTiles:
    ldh a, [hIsCGB]
    and a
    jr z, .byCPU
    ld a, h
    ldh [rHDMA1], a
    ld a, l
    ldh [rHDMA2], a
    ld a, d
    ldh [rHDMA3], a
    ld a, e
    ldh [rHDMA4], a
    ld a, c
    dec a
    ldh [rHDMA5], a         ; 16 bytes per tile; the CPU waits 32 cycles per tile
    ret
.byCPU:                     ; original Game Boy: pop the tiles off the stack, 16 bytes per loop
    ld [wSavedSP], sp
    ld sp, hl
    ld h, d
    ld l, e
.tile:
    REPT 8
        pop de
        ld a, e
        ld [hl+], a
        ld a, d
        ld [hl+], a
    ENDR
    dec c
    jr nz, .tile
    jp RestoreSP

; Copy a 32-wide padded map from HL to $9800 (in the current VRAM bank).
CopyMap:
    ldh a, [hIsCGB]
    and a
    jr z, .byCPU
    ld a, h
    ldh [rHDMA1], a
    ld a, l
    ldh [rHDMA2], a
    ld a, $98
    ldh [rHDMA3], a
    xor a
    ldh [rHDMA4], a
    ld a, MAP_H * 32 / 16 - 1
    ldh [rHDMA5], a
    ret
.byCPU:
    ld [wSavedSP], sp
    ld sp, hl
    ld hl, $9800
    ld b, MAP_H
.row:
    REPT MAP_W / 2
        pop de
        ld a, e
        ld [hl+], a
        ld a, d
        ld [hl+], a
    ENDR
    add sp, 32 - MAP_W      ; skip the off-screen padding
    ld a, l                 ; HL += 32 - MAP_W
    add 32 - MAP_W
    ld l, a
    adc h
    sub l
    ld h, a
    dec b
    jr nz, .row
RestoreSP:
    ld hl, wSavedSP
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    ld sp, hl
    ret

; Palette numbers live in VRAM bank 1 on Game Boy Color; the original has no such thing.
CopyAttr:
    ldh a, [hIsCGB]
    and a
    ret z
    ld a, 1
    ldh [rVBK], a
    call CopyMap
    xor a
    ldh [rVBK], a
    ret

; Upload the current scene's palettes at the current fade step (step 0 = the real colors).
UploadPalettes:
    xor a
    ldh [hPalDirty], a
    ldh a, [hFadeStep]
    ld b, a
    ldh a, [hIsCGB]
    and a
    jr z, .original
    ld a, b
    add a
    add LOW(FadeColor)
    ld l, a
    adc HIGH(FadeColor)
    sub l
    ld h, a
    ld a, [hl+]
    ld e, a
    ld d, [hl]
    ldh a, [hScene]
    add a
    add LOW(ScenePalettes)
    ld l, a
    adc HIGH(ScenePalettes)
    sub l
    ld h, a
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    jp hl
.original:
    ld a, b
    add LOW(FadeGray)
    ld l, a
    adc HIGH(FadeGray)
    sub l
    ld h, a
    ld a, [hl]
    ldh [rBGP], a
    ret

ScenePalettes:
    dw Scene0Palettes, Scene1Palettes

Scene0Palettes:
    ld h, d
    ld l, e
    ld c, LOW(rBCPD)
    ld a, $80 | 0
    ldh [rBCPS], a
    REPT 8
        ld a, [hl+]
        ldh [c], a
    ENDR
    ret
Scene1Palettes:
    ld h, d
    ld l, e
    ld c, LOW(rBCPD)
    ld de, 8
    add hl, de
    ld a, $80 | 8
    ldh [rBCPS], a
    REPT 8
        ld a, [hl+]
        ldh [c], a
    ENDR
    ret

SECTION "Data: Palettes", ROM0
FadeColor:                  ; RGB555: 2 background palettes per fade step
    dw FadeColor.step0, FadeColor.step1, FadeColor.step2, FadeColor.step3, FadeColor.step4
.step0:
    dw $63FF, $7E92, $48E6, $1821
    dw $63FC, $2B31, $21E6, $10A1
.step1:
    dw $6BFF, $7EF5, $55AC, $3129
    dw $6BFD, $3F75, $3A6C, $2D89
.step2:
    dw $73FF, $7F59, $6673, $4E10
    dw $73FE, $5798, $52F3, $4A50
.step3:
    dw $77FF, $7F9C, $7339, $6718
    dw $77FE, $6BDC, $6779, $6338
.step4:
    dw $7FFF, $7FFF, $7FFF, $7FFF
    dw $7FFF, $7FFF, $7FFF, $7FFF
FadeGray:                   ; original Game Boy BGP per fade step
    db %11100100, %10010000, %01000000, %00000000, %00000000

SECTION "Code: Frame", ROM0
; Point the update trampoline at the current scene's own update routine.
SetSceneUpdate:
    ldh a, [hScene]
    add a
    add LOW(SceneUpdates)
    ld l, a
    adc HIGH(SceneUpdates)
    sub l
    ld h, a
    ld a, [hl+]
    ldh [hUpdateJump + 1], a
    ld a, [hl]
    ldh [hUpdateJump + 2], a
    ret

SceneUpdates:
    dw Scene0Update, Scene1Update

NoUpdate:
    ret

; Fade out, then load scene A.
StartTransition:
    ldh [hNextScene], a
    ld a, FADE_FRAMES
    ldh [hTimer], a
    SET_UPDATE FadeOut
    ret

FadeOut:
    ld hl, hTimer
    dec [hl]
    ret nz
    ld [hl], FADE_FRAMES
    ldh a, [hFadeStep]
    cp FADE_STEPS
    jr z, .load             ; the last step has been on screen for a full step: load
    inc a
    ldh [hFadeStep], a
    ld a, 1
    ldh [hPalDirty], a
    ret
.load:
    ldh a, [hNextScene]
    jp LoadScene

FadeIn:
    ld hl, hTimer
    dec [hl]
    ret nz
    ld [hl], FADE_FRAMES
    ld hl, hFadeStep
    dec [hl]
    ld a, 1
    ldh [hPalDirty], a
    ld a, [hl]
    and a
    ret nz
    jp SetSceneUpdate       ; fully faded in: hand over to the scene

Scene0Update:              ; press-start screen: wait for Start or A
    ldh a, [hPadNew]
    and PADF_A | PADF_START
    jr nz, .press
    ldh a, [hFrame]         ; the prompt blinks every 32 frames
    and 31
    ret nz
    ldh a, [hPromptHidden]
    xor 1
    ldh [hPromptHidden], a
    ld hl, Scene0PromptShown
    jr z, .queue
    ld hl, Scene0PromptHidden
.queue:
    QUEUE_PATCH Scene0PromptPatch
    ret
.press:
    ld a, SFX_PRESS_START
    call PlaySfx
    ld a, 5
    ldh [hCounter], a
    ld a, 1
    ldh [hTimer], a
    SET_UPDATE Scene0Press
    ldh a, [hPromptHidden]  ; make sure the prompt is showing
    and a
    ret z
    xor a
    ldh [hPromptHidden], a
    ld hl, Scene0PromptShown
    QUEUE_PATCH Scene0PromptPatch
    ret

Scene0Press:              ; flip the flash area, then go
    ld hl, hTimer
    dec [hl]
    ret nz
    ld [hl], BLINK_FRAMES
    ld hl, hCounter
    ld a, [hl]
    and a
    jr z, .go
    dec [hl]
    and 1                   ; odd counts show the pressed frame, so it ends pressed
    ld hl, Scene0AreaPressed
    jr nz, .queue
    ld hl, Scene0AreaNormal
.queue:
    QUEUE_PATCH Scene0AreaPatch
    ret
.go:
    ld a, 1
    jp StartTransition

Scene1Update:              ; B goes back
    ldh a, [hPadNew]
    and PADF_B
    ret z
    ld a, SFX_MENU_BACK
    call PlaySfx
    ld a, 0
    jp StartTransition

SECTION "Code: Map patches", ROM0
Scene0PromptPatch:                ; prompt
    ld de, $9800 + 420
    REPT 11
        ld a, [hl+]
        ld [de], a
        inc e
    ENDR
    ret

Scene0AreaPatch:                ; flash area, 16x3 tiles
    ld de, $9800 + 162
    REPT 16
        ld a, [hl+]
        ld [de], a
        inc e
    ENDR
    ld de, $9800 + 194
    REPT 16
        ld a, [hl+]
        ld [de], a
        inc e
    ENDR
    ld de, $9800 + 226
    REPT 16
        ld a, [hl+]
        ld [de], a
        inc e
    ENDR
    ret

SECTION "Data: Menus and screens", ROM0
Scene0PromptShown:
    db $24, $25, $26, $27, $27, $01, $27, $28, $29, $25, $28
Scene0PromptHidden:
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01
Scene0AreaNormal:
    db $01, $0F, $10, $11, $12, $01, $01, $13, $14, $15, $16, $0F, $10, $17, $18, $01
    db $01, $19, $1A, $1B, $1C, $01, $01, $1D, $1E, $1F, $20, $19, $1A, $21, $22, $01
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01
Scene0AreaPressed:
    db $43, $44, $45, $46, $47, $48, $48, $49, $4A, $4B, $4C, $44, $45, $4D, $4E, $4F
    db $50, $51, $52, $53, $54, $08, $08, $55, $56, $57, $58, $51, $52, $59, $5A, $5B
    db $5C, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5D, $5E

; ---- Sound effects: three voices (pulse 1, pulse 2, noise), one effect each at a time --------
; PlaySfx starts an effect if its priority is at least that of what the voice is playing.
; SfxUpdate runs once a frame and steps each playing effect.

DEF rNR10 EQU $FF10
DEF rNR11 EQU $FF11
DEF rNR12 EQU $FF12
DEF rNR13 EQU $FF13
DEF rNR14 EQU $FF14
DEF rNR21 EQU $FF16
DEF rNR22 EQU $FF17
DEF rNR23 EQU $FF18
DEF rNR24 EQU $FF19
DEF rNR42 EQU $FF21
DEF rNR43 EQU $FF22
DEF rNR44 EQU $FF23
DEF rNR50 EQU $FF24
DEF rNR51 EQU $FF25
DEF rNR52 EQU $FF26

SECTION "Sound effect voices", WRAM0
; per voice: pointer to the next step (0 = idle), frames left, priority, duty, transpose
wSfx: ds 3 * 6
DEF SFX_PTR EQU 0
DEF SFX_TIMER EQU 2
DEF SFX_PRIORITY EQU 3
DEF SFX_DUTY EQU 4
DEF SFX_TRANSPOSE EQU 5

SECTION "Code: Sound effects", ROM0

SfxInit:
    ld a, $80               ; sound on
    ldh [rNR52], a
    ld a, $FF               ; every channel to both speakers
    ldh [rNR51], a
    ld a, $77               ; full volume
    ldh [rNR50], a
    ld hl, wSfx
    ld b, 3 * 6
    xor a
.clear:
    ld [hl+], a
    dec b
    jr nz, .clear
    ret

; Start effect A, transposed up hSfxTranspose semitones. Keeps BC, DE, HL.
PlaySfx:
    push hl
    push de
    push bc
    add a
    add LOW(SfxTable)
    ld l, a
    adc HIGH(SfxTable)
    sub l
    ld h, a
    ld a, [hl+]
    ld h, [hl]
    ld l, a                 ; HL = effect header
    ld a, [hl+]             ; voice
    ld b, a
    add a                   ; voice * 6
    add b
    add a
    add LOW(wSfx)
    ld e, a
    adc HIGH(wSfx)
    sub e
    ld d, a                 ; DE = voice slot
    ld a, [hl+]             ; priority
    ld c, a
    push hl
    ld hl, SFX_PTR + 1
    add hl, de
    ld a, [hl]              ; idle voices (pointer high byte 0) always take a new effect
    and a
    jr z, .take
    inc hl
    inc hl                  ; SFX_PRIORITY
    ld a, [hl]
    cp c
    jr z, .take
    jr c, .take
    pop hl
    jr .done                ; something more important is playing
.take:
    pop hl
    ld a, [hl+]             ; duty
    push af
    ld a, b                 ; pulse 1: set the sweep now
    and a
    ld a, [hl+]
    jr nz, .noSweep
    ldh [rNR10], a
.noSweep:
    ld a, l                 ; pointer to the first step
    ld [de], a
    inc de
    ld a, h
    ld [de], a
    inc de
    ld a, 1                 ; play the first step on the next update
    ld [de], a
    inc de
    ld a, c
    ld [de], a
    inc de
    pop af
    ld [de], a
    inc de
    ldh a, [hSfxTranspose]
    ld [de], a
.done:
    xor a
    ldh [hSfxTranspose], a
    pop bc
    pop de
    pop hl
    ret

SfxUpdate:
    ld hl, wSfx
    ld b, 0                 ; voice
.voice:
    ld a, [hl+]
    ld e, a
    ld a, [hl+]
    ld d, a                 ; DE = next step
    or e
    jr z, .next
    dec [hl]                ; frames left
    jr nz, .next
    ld a, [de]              ; step: frames (0 = the end), envelope, note / noise
    inc de
    and a
    jr z, .finish
    ld [hl], a
    push hl
    ld a, [de]
    inc de
    ld c, a                 ; C = envelope
    ld a, [de]
    inc de
    push af
    dec hl
    ld a, d                 ; store the pointer to the step after this one
    ld [hl-], a
    ld [hl], e
    pop af                  ; A = note / noise
    ld e, a
    inc hl
    inc hl
    inc hl
    inc hl                  ; SFX_DUTY
    ld a, [hl+]
    ld d, a                 ; D = duty
    ld a, b
    cp 2
    jr z, .noise
    ld a, e                 ; a pulse note: 0 is a rest
    and a
    jr z, .rest
    add [hl]                ; + transpose
    cp SFX_NOTE_TOP + 1
    jr c, .inRange
    ld a, SFX_NOTE_TOP
.inRange:
    add a
    add LOW(SfxNotes)
    ld l, a
    adc HIGH(SfxNotes)
    sub l
    ld h, a
    ld a, [hl+]
    ld e, a                 ; E = period low
    ld a, [hl]
    or $80                  ; trigger
    ld h, a
    ld a, b
    and a
    jr nz, .pulse2
    ld a, d
    ldh [rNR11], a
    ld a, c
    ldh [rNR12], a
    ld a, e
    ldh [rNR13], a
    ld a, h
    ldh [rNR14], a
    jr .played
.pulse2:
    ld a, d
    ldh [rNR21], a
    ld a, c
    ldh [rNR22], a
    ld a, e
    ldh [rNR23], a
    ld a, h
    ldh [rNR24], a
    jr .played
.rest:
    ld c, 0                 ; silence: the envelope off
    ld a, b
    and a
    ld a, c
    jr nz, .restPulse2
    ldh [rNR12], a
    jr .played
.restPulse2:
    ldh [rNR22], a
    jr .played
.noise:
    ld a, c
    ldh [rNR42], a
    ld a, e
    ldh [rNR43], a
    ld a, $80
    ldh [rNR44], a
.played:
    pop hl
.next:
    ld a, l                 ; to the next voice slot (6 bytes each; HL is 2 in)
    add 4
    ld l, a
    adc h
    sub l
    ld h, a
    inc b
    ld a, b
    cp 3
    jp c, .voice
    ret
.finish:                    ; the effect ended: free the voice and fade it out
    dec hl
    dec hl
    xor a
    ld [hl+], a             ; pointer
    ld [hl+], a
    ld [hl+], a             ; timer
    ld [hl], a              ; priority
    dec hl
    ld a, b
    and a
    jr nz, .notPulse1
    xor a
    ldh [rNR12], a
    jr .next
.notPulse1:
    cp 1
    jr nz, .notPulse2
    xor a
    ldh [rNR22], a
    jr .next
.notPulse2:
    xor a
    ldh [rNR42], a
    jr .next

SECTION "Data: Sound effects", ROM0
SfxTable:
    dw Sfx_menu_move
    dw Sfx_menu_confirm
    dw Sfx_menu_back
    dw Sfx_option_change
    dw Sfx_press_start
Sfx_menu_move:
    db 1, 1, 128, 0   ; voice, priority, duty, sweep
    db 2, $91, $35
    db 2, $51, $30
    db 0
Sfx_menu_confirm:
    db 0, 3, 64, 0   ; voice, priority, duty, sweep
    db 2, $C0, $31
    db 2, $C0, $35
    db 2, $C0, $38
    db 6, $C2, $3D
    db 0
Sfx_menu_back:
    db 0, 3, 128, 0   ; voice, priority, duty, sweep
    db 2, $A0, $2C
    db 5, $A2, $25
    db 0
Sfx_option_change:
    db 1, 1, 64, 0   ; voice, priority, duty, sweep
    db 2, $91, $2E
    db 2, $61, $35
    db 0
Sfx_press_start:
    db 0, 4, 128, 0   ; voice, priority, duty, sweep
    db 2, $D0, $25
    db 2, $D0, $29
    db 2, $D0, $2C
    db 2, $D0, $31
    db 2, $D0, $35
    db 2, $D0, $38
    db 10, $D3, $3D
    db 0
SfxNotes:                   ; period for note index 1 (C2) upward; index 0 unused
    dw 0, 44, 157, 263, 363, 457, 547, 631, 711, 786, 856, 923, 986, 1046, 1102, 1155, 1205, 1253, 1297, 1339, 1379, 1417, 1452, 1486, 1517, 1547, 1575, 1602, 1627, 1650, 1673, 1694, 1714, 1732, 1750, 1767, 1783, 1798, 1812, 1825, 1837, 1849, 1860, 1871, 1881, 1890, 1899, 1907, 1915, 1923, 1930, 1936, 1943, 1949, 1954, 1959, 1964, 1969, 1974, 1978, 1982, 1985, 1989, 1992, 1995, 1998, 2001, 2004, 2006, 2009, 2011, 2013, 2015

SECTION "Data: Scene 0 tiles", ROM0, ALIGN[4]   ; DMA needs 16-byte alignment
Scene0Tiles:              ; "Title": 95 unique tiles
    db $FF, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db $7F, $7F, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FC, $FC, $F0, $F0, $E0, $E0, $C0, $C0
    db $FF, $FF, $FF, $FF, $FF, $FF, $DF, $DF, $03, $01, $01, $00, $01, $00, $00, $00
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $FF, $3F, $FF, $1F
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $FE, $FF, $FF
    db $80, $80, $80, $80, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $FF, $0F, $FF, $0F, $FF, $07, $7F, $07, $FF, $07, $FF, $07, $FF, $03, $FF, $07
    db $00, $00, $00, $00, $00, $00, $80, $80, $C0, $80, $FD, $C0, $FF, $E0, $FF, $F0
    db $01, $00, $01, $00, $03, $00, $07, $00, $1F, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $07, $FF, $07, $FF, $07, $FF, $0F, $FF, $0F, $FF, $1F, $FF, $3F, $FF, $7F
    db $FF, $FC, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db $FF, $01, $FF, $DF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    db $CF, $CF, $CF, $C7, $C3, $C3, $C3, $C1, $CC, $C0, $CC, $C4, $CC, $C4, $CC, $C4
    db $CF, $CF, $CF, $C7, $0F, $07, $0F, $07, $CF, $87, $CF, $47, $CF, $47, $CF, $47
    db $CF, $CF, $CF, $C7, $CF, $C7, $CF, $C7, $F3, $E3, $F3, $F1, $FC, $F8, $FC, $FC
    db $CF, $CF, $CF, $C7, $CF, $C7, $CF, $C7, $3F, $27, $3F, $1F, $FF, $9F, $FF, $7F
    db $F0, $F0, $F0, $F0, $CF, $C8, $CF, $C7, $CF, $C7, $CF, $C7, $CC, $C4, $CC, $C4
    db $3F, $3F, $3F, $1F, $CF, $0F, $CF, $C7, $FF, $E7, $FF, $FF, $0F, $0F, $0F, $07
    db $F0, $F0, $F0, $F0, $CF, $C8, $CF, $C7, $CF, $C7, $CF, $C7, $C0, $C0, $C0, $C0
    db $3F, $3F, $3F, $1F, $CF, $0F, $CF, $C7, $CF, $C7, $CF, $C7, $0F, $07, $0F, $07
    db $C0, $C0, $C0, $C0, $CF, $C0, $CF, $C7, $CF, $C7, $CF, $C7, $C0, $C0, $C0, $C0
    db $0F, $0F, $0F, $07, $FF, $07, $FF, $FF, $FF, $FF, $FF, $FF, $3F, $3F, $3F, $1F
    db $CF, $C6, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $FF, $E7, $FF, $FF
    db $CF, $47, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $FF, $E7, $FF, $FF
    db $FC, $FC, $FC, $FC, $FC, $FC, $FC, $FC, $FC, $FC, $FC, $FC, $FF, $FE, $FF, $FF
    db $FF, $7F, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $7F, $FF, $FF
    db $CF, $C6, $CF, $C7, $CF, $C7, $CF, $C7, $F0, $E0, $F0, $F0, $FF, $F8, $FF, $FF
    db $CF, $07, $CF, $C7, $CF, $C7, $CF, $C7, $0F, $07, $0F, $07, $FF, $07, $FF, $FF
    db $CF, $C0, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $FF, $E7, $FF, $FF
    db $CF, $07, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $CF, $C7, $FF, $E7, $FF, $FF
    db $CF, $C0, $CF, $C7, $CF, $C7, $CF, $C7, $C0, $C0, $C0, $C0, $FF, $E0, $FF, $FF
    db $FF, $1F, $FF, $FF, $FF, $FF, $FF, $FF, $0F, $0F, $0F, $07, $FF, $07, $FF, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $7F, $FF, $FF, $FF, $FF, $FF, $FF
    db $87, $87, $BB, $BB, $BB, $BB, $87, $87, $BF, $BF, $BF, $BF, $BF, $BF, $FF, $FF
    db $87, $87, $BB, $BB, $BB, $BB, $87, $87, $AF, $AF, $B7, $B7, $BB, $BB, $FF, $FF
    db $83, $83, $BF, $BF, $BF, $BF, $87, $87, $BF, $BF, $BF, $BF, $83, $83, $FF, $FF
    db $C3, $C3, $BF, $BF, $BF, $BF, $C7, $C7, $FB, $FB, $FB, $FB, $87, $87, $FF, $FF
    db $83, $83, $EF, $EF, $EF, $EF, $EF, $EF, $EF, $EF, $EF, $EF, $EF, $EF, $FF, $FF
    db $C7, $C7, $BB, $BB, $BB, $BB, $83, $83, $BB, $BB, $BB, $BB, $BB, $BB, $FF, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FC, $FC, $FB, $F8, $E7, $E0, $DF, $C0, $3F
    db $FF, $FF, $FF, $E0, $E0, $1F, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $3F, $3F, $CF, $0F, $F3, $03, $FC, $00, $FF, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $3F, $3F, $CF, $0F, $F7
    db $FF, $FF, $FF, $FF, $FF, $7F, $7F, $BF, $3F, $CF, $0F, $F7, $07, $F9, $01, $FE
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $F8, $F8, $C7, $C0, $3F
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $C1, $C1, $3E, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $FE, $C1, $C0, $3F, $00, $FF
    db $FF, $FE, $FE, $F9, $F8, $F7, $F0, $CF, $C0, $3F, $00, $FF, $00, $FF, $00, $FF
    db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $07, $F9, $01, $FE, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $7F, $7F, $8F, $0F, $F0, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $00, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $3F, $3F, $C7, $07, $F9, $01, $FE, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $7F, $7F, $9F
    db $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FE, $FE, $FD
    db $FF, $FE, $FE, $FD, $FC, $FB, $F8, $E7, $E0, $DF, $C0, $BF, $80, $7F, $00, $FF
    db $7F, $9F, $1F, $E0, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FE, $F1, $F0, $0F, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $1F, $E3, $03, $FC, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FF, $FF, $FF, $FF, $FF, $00, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FC, $F3, $F0, $CF, $C0, $3F, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $FF, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00
    db $FF, $30, $30, $38, $3C, $3C, $3C, $3E, $33, $3F, $33, $3B, $33, $3B, $33, $3B
    db $FF, $30, $30, $38, $F0, $F8, $F0, $F8, $30, $78, $30, $B8, $30, $B8, $30, $B8
    db $FF, $30, $30, $38, $30, $38, $30, $38, $0C, $1C, $0C, $0E, $03, $07, $03, $03
    db $FF, $30, $30, $38, $30, $38, $30, $38, $C0, $D8, $C0, $E0, $00, $60, $00, $80
    db $FF, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $FF, $0F, $0F, $0F, $30, $37, $30, $38, $30, $38, $30, $38, $33, $3B, $33, $3B
    db $FF, $C0, $C0, $E0, $30, $F0, $30, $38, $00, $18, $00, $00, $F0, $F0, $F0, $F8
    db $FF, $0F, $0F, $0F, $30, $37, $30, $38, $30, $38, $30, $38, $3F, $3F, $3F, $3F
    db $FF, $C0, $C0, $E0, $30, $F0, $30, $38, $30, $38, $30, $38, $F0, $F8, $F0, $F8
    db $FF, $3F, $3F, $3F, $30, $3F, $30, $38, $30, $38, $30, $38, $3F, $3F, $3F, $3F
    db $FF, $F0, $F0, $F8, $00, $F8, $00, $00, $00, $00, $00, $00, $C0, $C0, $C0, $E0
    db $FF, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00
    db $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00
    db $30, $39, $30, $38, $30, $38, $30, $38, $30, $38, $30, $38, $00, $18, $00, $00
    db $30, $B8, $30, $38, $30, $38, $30, $38, $30, $38, $30, $38, $00, $18, $00, $00
    db $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $03, $00, $01, $00, $00
    db $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $00
    db $30, $39, $30, $38, $30, $38, $30, $38, $0F, $1F, $0F, $0F, $00, $07, $00, $00
    db $30, $F8, $30, $38, $30, $38, $30, $38, $F0, $F8, $F0, $F8, $00, $F8, $00, $00
    db $30, $3F, $30, $38, $30, $38, $30, $38, $30, $38, $30, $38, $00, $18, $00, $00
    db $30, $F8, $30, $38, $30, $38, $30, $38, $30, $38, $30, $38, $00, $18, $00, $00
    db $30, $3F, $30, $38, $30, $38, $30, $38, $3F, $3F, $3F, $3F, $00, $1F, $00, $00
    db $00, $E0, $00, $00, $00, $00, $00, $00, $F0, $F0, $F0, $F8, $00, $F8, $00, $00
    db $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00
    db $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $80, $00, $FF, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $FF, $00
    db $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $01, $00, $FF, $00

SECTION "Data: Scene 0 maps", ROM0, ALIGN[4]    ; rows padded to 32 tiles so DMA can copy them whole
Scene0Map:
    db $00, $01, $01, $01, $00, $01, $01, $01, $02, $01, $01, $01, $02, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $03, $04, $05, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $01, $01, $01, $02, $01, $01, $01, $01, $01, $01, $01, $02, $01, $06, $07, $08, $09, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $0A, $0B, $0C, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $00, $01, $01, $01, $02, $01, $01, $01, $00, $01, $01, $0D, $0E, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $0F, $10, $11, $12, $01, $01, $13, $14, $15, $16, $0F, $10, $17, $18, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $01, $01, $19, $1A, $1B, $1C, $01, $01, $1D, $1E, $1F, $20, $19, $1A, $21, $22, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $23, $01, $01, $01, $00, $01, $01, $01, $01, $01, $01, $01, $00, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $01, $01, $01, $00, $01, $01, $01, $00, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $02, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $01, $01, $01, $02, $01, $01, $01, $00, $01, $01, $01, $01, $01, $01, $01, $00, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $24, $25, $26, $27, $27, $01, $27, $28, $29, $25, $28, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $2A, $2B, $2C, $2D, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $2E, $2F, $30, $31, $32, $33, $34, $35, $36, $36, $36, $37, $38, $39, $39, $3A, $3B, $01, $3C, $3D, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $36, $3E, $3F, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $40, $41, $42, $36, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $36, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
Scene0Attr:               ; palette number per tile (Game Boy Color only)
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "Data: Scene 1 tiles", ROM0, ALIGN[4]   ; DMA needs 16-byte alignment
Scene1Tiles:              ; "Game": 22 unique tiles
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $0F, $FF, $0F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $33, $FF, $33
    db $FF, $C0, $FF, $C0, $FF, $30, $FF, $30, $FF, $00, $FF, $00, $FF, $F0, $FF, $F0
    db $FF, $0F, $FF, $0F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F
    db $FF, $C0, $FF, $C0, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $F0, $FF, $F0
    db $FF, $30, $FF, $30, $FF, $3C, $FF, $3C, $FF, $33, $FF, $33, $FF, $33, $FF, $33
    db $FF, $30, $FF, $30, $FF, $F0, $FF, $F0, $FF, $30, $FF, $30, $FF, $30, $FF, $30
    db $FF, $3F, $FF, $3F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F
    db $FF, $F0, $FF, $F0, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $C0, $FF, $C0
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $0F, $FF, $0F, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $F0, $FF, $F0, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F, $FF, $00, $FF, $00
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $F0, $FF, $F0, $FF, $00, $FF, $00
    db $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $04, $FF, $04, $FF, $04, $FF, $00
    db $FF, $87, $FF, $44, $FF, $44, $FF, $87, $FF, $05, $FF, $04, $FF, $04, $FF, $00
    db $FF, $87, $FF, $44, $FF, $44, $FF, $87, $FF, $04, $FF, $84, $FF, $47, $FF, $00
    db $FF, $C3, $FF, $04, $FF, $04, $FF, $83, $FF, $00, $FF, $00, $FF, $C7, $FF, $00
    db $FF, $C3, $FF, $04, $FF, $04, $FF, $83, $FF, $40, $FF, $40, $FF, $87, $FF, $00
    db $FF, $C0, $FF, $00, $FF, $00, $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $00
    db $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $00
    db $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $00

SECTION "Data: Scene 1 maps", ROM0, ALIGN[4]    ; rows padded to 32 tiles so DMA can copy them whole
Scene1Map:
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $01, $02, $03, $04, $05, $06, $07, $08, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $09, $0A, $0B, $0B, $0B, $0B, $0C, $0D, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $0E, $0F, $10, $11, $12, $13, $14, $15, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
Scene1Attr:               ; palette number per tile (Game Boy Color only)
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "Variables", HRAM
hIsCGB: db
hScene: db
hVars:
hUpdateJump: ds 3        ; JP to the current update routine
hFrame: db
hPad: db
hPadNew: db
hTimer: db
hNextScene: db
hSfxTranspose: db       ; semitones up for the next PlaySfx
hFadeStep: db
hPalDirty: db
hCounter: db
hPatchJump: ds 3         ; JP to the pending map patch
hPatchSrc: dw
hPatchPending: db
hPromptHidden: db
hVarsEnd:
