; Generated by gbstage from "My Game". Changes here are overwritten on the next build.

DEF rP1    EQU $FF00
DEF rIF    EQU $FF0F
DEF rLCDC  EQU $FF40
DEF rSCY   EQU $FF42
DEF rSCX   EQU $FF43
DEF rLY    EQU $FF44
DEF rBGP   EQU $FF47
DEF rOBP0  EQU $FF48
DEF rVBK   EQU $FF4F
DEF rHDMA1 EQU $FF51
DEF rHDMA2 EQU $FF52
DEF rHDMA3 EQU $FF53
DEF rHDMA4 EQU $FF54
DEF rHDMA5 EQU $FF55
DEF rBCPS  EQU $FF68
DEF rBCPD  EQU $FF69
DEF rOCPS  EQU $FF6A
DEF rOCPD  EQU $FF6B
DEF rIE    EQU $FFFF
DEF OAM_CURSOR EQU $FE00

DEF MAP_W EQU 20
DEF MAP_H EQU 18
DEF FADE_STEPS EQU 4
DEF FADE_FRAMES EQU 3
DEF BLINK_FRAMES EQU 4
DEF LCDC_ON EQU %10000011

; joypad bits in hPad / hPadNew (d-pad in the high nibble)
DEF PAD_A EQU 0
DEF PAD_B EQU 1
DEF PAD_START EQU 3
DEF PAD_UP EQU 6
DEF PAD_DOWN EQU 7
DEF PADF_A EQU 1 << PAD_A
DEF PADF_B EQU 1 << PAD_B
DEF PADF_START EQU 1 << PAD_START
DEF PAD_RIGHT EQU 4
DEF PAD_LEFT EQU 5
DEF PADF_UP EQU 1 << PAD_UP
DEF PADF_DOWN EQU 1 << PAD_DOWN
DEF PADF_LEFT EQU 1 << PAD_LEFT
DEF PADF_RIGHT EQU 1 << PAD_RIGHT
DEF SFX_MENU_MOVE EQU 0
DEF SFX_MENU_CONFIRM EQU 1
DEF SFX_MENU_BACK EQU 2
DEF SFX_OPTION_CHANGE EQU 3
DEF SFX_PRESS_START EQU 4
DEF SFX_MOVE EQU 5
DEF SFX_MOVE_HELD EQU 6
DEF SFX_ROTATE EQU 7
DEF SFX_LAND EQU 8
DEF SFX_CLEAR EQU 9
DEF SFX_VIRUS EQU 10
DEF SFX_WIN EQU 11
DEF SFX_LOSE EQU 12

MACRO PZ_SFX                ; play sound effect \1
    ld a, \1
    call PlaySfx
ENDM

MACRO PZ_SFX_A              ; play sound effect A
    call PlaySfx
ENDM

MACRO PZ_CLEAR_SFX          ; play the clear sound A semitones up
    ldh [hSfxTranspose], a
    ld a, SFX_CLEAR
    call PlaySfx
ENDM
DEF REPEAT_DELAY EQU 16       ; frames a direction is held before it repeats
DEF REPEAT_RATE EQU 4         ; frames between repeats after that


MACRO QUEUE_PATCH           ; apply patch routine \1 to the tiles at HL during the next VBlank
    ld a, l
    ldh [hPatchSrc], a
    ld a, h
    ldh [hPatchSrc + 1], a
    ld a, LOW(\1)
    ldh [hPatchJump + 1], a
    ld a, HIGH(\1)
    ldh [hPatchJump + 2], a
    ld a, 1
    ldh [hPatchPending], a  ; set last
ENDM

MACRO SET_UPDATE            ; run \1 every frame from now on
    ld a, LOW(\1)
    ldh [hUpdateJump + 1], a
    ld a, HIGH(\1)
    ldh [hUpdateJump + 2], a
ENDM

SECTION "Header", ROM0[$100]
    nop
    jp Start
    ds $150 - @, 0

SECTION "Stack", WRAM0
    ds 64
wStackTop:
wSavedSP: dw

SECTION "Code: Start", ROM0
Start:
    ; The boot ROM leaves A = $11 on Game Boy Color hardware, and interrupts disabled (they stay that way).
    cp $11
    ld a, 0
    jr nz, .notCGB
    inc a
.notCGB:
    ldh [hIsCGB], a
    ld sp, wStackTop
.waitVBlank:                ; the LCD may only be switched off during VBlank
    ldh a, [rLY]
    cp 144
    jr c, .waitVBlank
.waitVBlankDone:            ; labels named .waitX/.waitXDone mark idle loops for the profiler
    xor a
    ldh [rLCDC], a
    ldh [rSCY], a
    ldh [rSCX], a
    ld hl, $FE00            ; clear OAM (it's random at power-on); A = 0
    ld b, 160
.clearOAM:
    ld [hl+], a
    dec b
    jr nz, .clearOAM
    ld a, 0
    ld [OAM_CURSOR + 3], a  ; cursor palette (Color) / OBP0 (original); tile 0
    ld hl, CursorTile       ; sprite tile 0
    ld de, $8000
    ld b, 16
.cursorTile:
    ld a, [hl+]
    ld [de], a
    inc e
    dec b
    jr nz, .cursorTile
    ld hl, hVars            ; clear the HRAM variables
    xor a
    ld b, hVarsEnd - hVars
.clearVars:
    ld [hl+], a
    dec b
    jr nz, .clearVars
    call SfxInit
    ld a, $C3               ; JP opcode for the update trampoline
    ldh [hUpdateJump], a
    ldh [hPatchJump], a     ; ... and for the patch trampoline
    ld a, 1                 ; VBlank wakes HALT; no interrupt handler ever runs
    ldh [rIE], a
    ld a, 0
    call LoadScene
MainLoop:
    xor a
    ldh [rIF], a
    halt                    ; sleep until VBlank
    nop                     ; HALT may run the next byte twice if VBlank arrives just before it
    ldh a, [hCursorY]       ; a few sprites: write them straight to OAM (cheaper than DMA)
    ld [OAM_CURSOR], a
    ldh a, [hCursorX]
    ld [OAM_CURSOR + 1], a
    ldh a, [hPalDirty]
    and a
    call nz, UploadPalettes
    ldh a, [hPatchPending]  ; a queued map patch (blink, flash, prompt)
    and a
    jr z, .noPatch
    xor a
    ldh [hPatchPending], a
    ld hl, hPatchSrc
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    call hPatchJump
.noPatch:
VBlankDone:                 ; everything that must happen during VBlank is done
    ld hl, hFrame
    inc [hl]
    ld a, $20               ; read the d-pad
    ldh [rP1], a
    ldh a, [rP1]
    ldh a, [rP1]
    cpl
    and $0F
    swap a
    ld b, a
    ld a, $10               ; read the buttons
    ldh [rP1], a
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    ldh a, [rP1]
    cpl
    and $0F
    or b
    ld b, a
    ld a, $30
    ldh [rP1], a
    ldh a, [hPad]
    xor b
    and b
    ldh [hPadNew], a        ; pressed this frame
    ld a, b
    ldh [hPad], a           ; held
    ld a, b                 ; repeat held directions
    and $F0
    jr z, .noRepeat
    ldh a, [hPadNew]
    and $F0
    jr z, .holding
    ld a, REPEAT_DELAY
    ldh [hRepeatTimer], a
    jr .noRepeat
.holding:
    ld hl, hRepeatTimer
    dec [hl]
    jr nz, .noRepeat
    ld [hl], REPEAT_RATE
    ld a, b
    and $F0
    ld c, a
    ldh a, [hPadNew]
    or c
    jr .repeat
.noRepeat:
    ldh a, [hPadNew]
.repeat:
    ldh [hPadRepeat], a
    call hUpdateJump
    call SfxUpdate
    jp MainLoop

SECTION "Code: Scenes", ROM0
; Load scene A with the screen off. Tiles, map and palette map go by DMA on Game Boy Color.
LoadScene:
    ldh [hScene], a
    ldh a, [rLCDC]
    add a                   ; screen already off (at boot)? bit 7 -> carry
    jr nc, .screenOff
.waitVBlank:
    ldh a, [rLY]
    cp 144
    jr c, .waitVBlank
.waitVBlankDone:
    xor a
    ldh [rLCDC], a
.screenOff:
    ldh a, [hScene]
    add a
    add LOW(SceneLoads)
    ld l, a
    adc HIGH(SceneLoads)
    sub l
    ld h, a
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    call JumpHL
    xor a
    ldh [hSel], a
    ldh [hPatchPending], a
    ld a, FADE_STEPS        ; start fully faded; FadeIn brings the colors up
    ldh [hFadeStep], a
    ld a, FADE_FRAMES
    ldh [hTimer], a
    SET_UPDATE FadeIn
    ldh a, [hCursorY]       ; OAM is writable while the screen is off
    ld [OAM_CURSOR], a
    ldh a, [hCursorX]
    ld [OAM_CURSOR + 1], a
    call UploadPalettes
    ld a, LCDC_ON
    ldh [rLCDC], a
    ret

JumpHL:
    jp hl

SceneLoads:
    dw Scene0Load, Scene1Load, Scene2Load

Scene0Load:
    ld hl, Scene0Tiles
    ld de, $9000            ; tiles 0-127
    ld c, 31
    call CopyTiles
    ld hl, Scene0Map
    call CopyMap
    ld hl, Scene0Attr
    call CopyAttr
    ld a, 96               ; cursor on the first item
    ldh [hCursorY], a
    ld a, 53
    ldh [hCursorX], a
    ret
Scene1Load:
    ld hl, Scene1Tiles
    ld de, $9000            ; tiles 0-127
    ld c, 22
    call CopyTiles
    ld hl, Scene1Map
    call CopyMap
    ld hl, Scene1Attr
    call CopyAttr
    xor a                   ; no menu: cursor off screen
    ldh [hCursorY], a
    ret
Scene2Load:
    ld hl, Scene2Tiles
    ld de, $9000            ; tiles 0-127
    ld c, 29
    call CopyTiles
    ld hl, Scene2Map
    call CopyMap
    ld hl, Scene2Attr
    call CopyAttr
    xor a                   ; no menu: cursor off screen
    ldh [hCursorY], a
    ret

; Copy C tiles (1-128) from HL to DE.
CopyTiles:
    ldh a, [hIsCGB]
    and a
    jr z, .byCPU
    ld a, h
    ldh [rHDMA1], a
    ld a, l
    ldh [rHDMA2], a
    ld a, d
    ldh [rHDMA3], a
    ld a, e
    ldh [rHDMA4], a
    ld a, c
    dec a
    ldh [rHDMA5], a         ; 16 bytes per tile; the CPU waits 32 cycles per tile
    ret
.byCPU:                     ; original Game Boy: pop the tiles off the stack, 16 bytes per loop
    ld [wSavedSP], sp
    ld sp, hl
    ld h, d
    ld l, e
.tile:
    REPT 8
        pop de
        ld a, e
        ld [hl+], a
        ld a, d
        ld [hl+], a
    ENDR
    dec c
    jr nz, .tile
    jp RestoreSP

; Copy a 32-wide padded map from HL to $9800 (in the current VRAM bank).
CopyMap:
    ldh a, [hIsCGB]
    and a
    jr z, .byCPU
    ld a, h
    ldh [rHDMA1], a
    ld a, l
    ldh [rHDMA2], a
    ld a, $98
    ldh [rHDMA3], a
    xor a
    ldh [rHDMA4], a
    ld a, MAP_H * 32 / 16 - 1
    ldh [rHDMA5], a
    ret
.byCPU:
    ld [wSavedSP], sp
    ld sp, hl
    ld hl, $9800
    ld b, MAP_H
.row:
    REPT MAP_W / 2
        pop de
        ld a, e
        ld [hl+], a
        ld a, d
        ld [hl+], a
    ENDR
    add sp, 32 - MAP_W      ; skip the off-screen padding
    ld a, l                 ; HL += 32 - MAP_W
    add 32 - MAP_W
    ld l, a
    adc h
    sub l
    ld h, a
    dec b
    jr nz, .row
RestoreSP:
    ld hl, wSavedSP
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    ld sp, hl
    ret

; Palette numbers live in VRAM bank 1 on Game Boy Color; the original has no such thing.
CopyAttr:
    ldh a, [hIsCGB]
    and a
    ret z
    ld a, 1
    ldh [rVBK], a
    call CopyMap
    xor a
    ldh [rVBK], a
    ret

; Upload the current scene's palettes at the current fade step (step 0 = the real colors).
UploadPalettes:
    xor a
    ldh [hPalDirty], a
    ldh a, [hFadeStep]
    ld b, a
    ldh a, [hIsCGB]
    and a
    jr z, .original
    ld a, b
    add a
    add LOW(FadeColor)
    ld l, a
    adc HIGH(FadeColor)
    sub l
    ld h, a
    ld a, [hl+]
    ld e, a
    ld d, [hl]
    ldh a, [hScene]
    add a
    add LOW(ScenePalettes)
    ld l, a
    adc HIGH(ScenePalettes)
    sub l
    ld h, a
    ld a, [hl+]
    ld h, [hl]
    ld l, a
    jp hl
.original:
    ld a, b
    add LOW(FadeGray)
    ld l, a
    adc HIGH(FadeGray)
    sub l
    ld h, a
    ld a, [hl]
    ldh [rBGP], a
    ldh [rOBP0], a
    ret

ScenePalettes:
    dw Scene0Palettes, Scene1Palettes, Scene2Palettes

Scene0Palettes:
    ld h, d
    ld l, e
    ld c, LOW(rBCPD)
    ld a, $80 | 0
    ldh [rBCPS], a
    ld b, 2
.palettes0:
    REPT 8
        ld a, [hl+]
        ldh [c], a
    ENDR
    dec b
    jr nz, .palettes0
    ld de, 8
    add hl, de
    ld a, $80 | 0
    ldh [rOCPS], a
    ld c, LOW(rOCPD)
    REPT 8
        ld a, [hl+]
        ldh [c], a
    ENDR
    ret
Scene1Palettes:
    ld h, d
    ld l, e
    ld c, LOW(rBCPD)
    ld de, 8
    add hl, de
    ld a, $80 | 8
    ldh [rBCPS], a
    REPT 8
        ld a, [hl+]
        ldh [c], a
    ENDR
    ret
Scene2Palettes:
    ld h, d
    ld l, e
    ld c, LOW(rBCPD)
    ld de, 16
    add hl, de
    ld a, $80 | 16
    ldh [rBCPS], a
    REPT 8
        ld a, [hl+]
        ldh [c], a
    ENDR
    ret

SECTION "Data: Palettes", ROM0
FadeColor:                  ; RGB555: 3 background + 1 sprite palettes per fade step
    dw FadeColor.step0, FadeColor.step1, FadeColor.step2, FadeColor.step3, FadeColor.step4
.step0:
    dw $7FFF, $7F54, $7208, $3082
    dw $63FC, $2B31, $21E6, $10A1
    dw $63DF, $3B1C, $19F4, $08A8
    dw $7FFF, $2B9F, $121E, $0048
.step1:
    dw $7FFF, $7F77, $768E, $4569
    dw $6BFD, $3F75, $3A6C, $2D89
    dw $6BDF, $4B5D, $3277, $258E
    dw $7FFF, $3FBF, $2E9E, $212E
.step2:
    dw $7FFF, $7FBA, $7B14, $5A51
    dw $73FE, $5798, $52F3, $4A50
    dw $73FF, $5F9E, $4EFA, $4654
    dw $7FFF, $57DF, $4B1F, $4234
.step3:
    dw $7FFF, $7FDC, $7B79, $6B18
    dw $77FE, $6BDC, $6779, $6338
    dw $77FF, $6FBE, $677C, $6339
    dw $7FFF, $6BDF, $637F, $5F19
.step4:
    dw $7FFF, $7FFF, $7FFF, $7FFF
    dw $7FFF, $7FFF, $7FFF, $7FFF
    dw $7FFF, $7FFF, $7FFF, $7FFF
    dw $7FFF, $7FFF, $7FFF, $7FFF
FadeGray:                   ; original Game Boy BGP/OBP0 per fade step
    db %11100100, %10010000, %01000000, %00000000, %00000000

SECTION "Code: Frame", ROM0
; Point the update trampoline at the current scene's own update routine.
SetSceneUpdate:
    ldh a, [hScene]
    add a
    add LOW(SceneUpdates)
    ld l, a
    adc HIGH(SceneUpdates)
    sub l
    ld h, a
    ld a, [hl+]
    ldh [hUpdateJump + 1], a
    ld a, [hl]
    ldh [hUpdateJump + 2], a
    ret

SceneUpdates:
    dw Scene0Update, Scene1Update, Scene2Update

NoUpdate:
    ret

; Fade out, then load scene A.
StartTransition:
    ldh [hNextScene], a
    ld a, FADE_FRAMES
    ldh [hTimer], a
    SET_UPDATE FadeOut
    ret

FadeOut:
    ld hl, hTimer
    dec [hl]
    ret nz
    ld [hl], FADE_FRAMES
    ldh a, [hFadeStep]
    cp FADE_STEPS
    jr z, .load             ; the last step has been on screen for a full step: load
    inc a
    ldh [hFadeStep], a
    ld a, 1
    ldh [hPalDirty], a
    ret
.load:
    ldh a, [hNextScene]
    jp LoadScene

FadeIn:
    ld hl, hTimer
    dec [hl]
    ret nz
    ld [hl], FADE_FRAMES
    ld hl, hFadeStep
    dec [hl]
    ld a, 1
    ldh [hPalDirty], a
    ld a, [hl]
    and a
    ret nz
    jp SetSceneUpdate       ; fully faded in: hand over to the scene

Scene0Update:              ; menu: up/down to move, A or Start to choose
    ldh a, [hPadRepeat]
    and a
    jr z, .cursor           ; nothing pressed: just animate
    ld b, a
    and PADF_UP | PADF_DOWN
    jr z, .notMove
    ld a, SFX_MENU_MOVE
    call PlaySfx
.notMove:
    bit PAD_DOWN, b
    jr z, .notDown
    ldh a, [hSel]
    inc a
    cp 2
    jr c, .down
    xor a
.down:
    ldh [hSel], a
.notDown:
    bit PAD_UP, b
    jr z, .notUp
    ldh a, [hSel]
    sub 1
    jr nc, .up
    ld a, 1
.up:
    ldh [hSel], a
.notUp:
    ldh a, [hPadNew]
    and PADF_A | PADF_START
    jr z, .cursor
    ld a, SFX_MENU_CONFIRM
    call PlaySfx
    ld a, 7
    ldh [hCounter], a
    ld a, 1
    ldh [hTimer], a
    SET_UPDATE Scene0Blink
.cursor:                    ; ease toward the chosen item: half the distance each frame
    ldh a, [hSel]
    add LOW(Scene0CursorY)
    ld l, a
    adc HIGH(Scene0CursorY)
    sub l
    ld h, a
    ldh a, [hCursorY]
    ld c, a
    ld a, [hl]
    sub c
    jr z, .yDone
    ld d, a
    sra a
    jr nz, .move
    ld a, d
.move:
    add c
    ldh [hCursorY], a
.yDone:
    ldh a, [hFrame]         ; the bob only changes every 8 frames
    ld b, a
    and 7
    ret nz
    ld a, b
    rrca
    rrca
    rrca
    and 7
    add LOW(BobTable)
    ld l, a
    adc HIGH(BobTable)
    sub l
    ld h, a
    ld a, [hl]
    add 53
    ldh [hCursorX], a
    ret

Scene0Blink:              ; flash the chosen item, then go to its scene
    ld hl, hTimer
    dec [hl]
    ret nz
    ld [hl], BLINK_FRAMES
    ld hl, hCounter
    dec [hl]
    jr z, .go
    ld b, [hl]
    ldh a, [hSel]
    add a
    ld e, a
    ld d, 0
    ld hl, Scene0ItemPatch  ; this item's patch routine
    add hl, de
    ld a, [hl+]
    ldh [hPatchJump + 1], a
    ld a, [hl]
    ldh [hPatchJump + 2], a
    ld hl, Scene0ItemShown  ; odd counts show the label, even counts hide it
    bit 0, b
    jr nz, .source
    ld hl, Scene0ItemHidden
.source:
    add hl, de
    ld a, [hl+]
    ldh [hPatchSrc], a
    ld a, [hl]
    ldh [hPatchSrc + 1], a
    ld a, 1
    ldh [hPatchPending], a  ; set last: the next VBlank applies the patch
    ret
.go:
    ldh a, [hSel]
    add LOW(Scene0ItemTarget)
    ld l, a
    adc HIGH(Scene0ItemTarget)
    sub l
    ld h, a
    ld a, [hl]
    jp StartTransition

Scene1Update:              ; B goes back
    ldh a, [hPadNew]
    and PADF_B
    ret z
    ld a, SFX_MENU_BACK
    call PlaySfx
    ld a, 0
    jp StartTransition

Scene2Update:              ; B goes back
    ldh a, [hPadNew]
    and PADF_B
    ret z
    ld a, SFX_MENU_BACK
    call PlaySfx
    ld a, 0
    jp StartTransition

SECTION "Code: Map patches", ROM0
Scene0Item0Patch:                ; menu item "START"
    ld de, $9800 + 327
    REPT 5
        ld a, [hl+]
        ld [de], a
        inc e
    ENDR
    ret

Scene0Item1Patch:                ; menu item "OPTIONS"
    ld de, $9800 + 391
    REPT 7
        ld a, [hl+]
        ld [de], a
        inc e
    ENDR
    ret

SECTION "Data: Menus and screens", ROM0
Scene0CursorY:
    db 96, 112
Scene0ItemTarget:
    db 1, 2
Scene0ItemPatch:
    dw Scene0Item0Patch, Scene0Item1Patch
Scene0ItemShown:
    dw .shown0, .shown1
.shown0:
    db $15, $16, $17, $18, $16
.shown1:
    db $19, $1A, $16, $1B, $19, $1C, $15
Scene0ItemHidden:
    dw .hidden0, .hidden1
.hidden0:
    db $00, $00, $00, $00, $00
.hidden1:
    db $00, $00, $00, $00, $00, $00, $00

SECTION "Data: Sprites", ROM0
CursorTile:
    db $20, $20, $30, $30, $38, $28, $34, $2C, $38, $28, $30, $30, $20, $20, $00, $00
BobTable:
    db 0, 0, 1, 2, 2, 2, 1, 0

; ---- Sound effects: three voices (pulse 1, pulse 2, noise), one effect each at a time --------
; PlaySfx starts an effect if its priority is at least that of what the voice is playing.
; SfxUpdate runs once a frame and steps each playing effect.

DEF rNR10 EQU $FF10
DEF rNR11 EQU $FF11
DEF rNR12 EQU $FF12
DEF rNR13 EQU $FF13
DEF rNR14 EQU $FF14
DEF rNR21 EQU $FF16
DEF rNR22 EQU $FF17
DEF rNR23 EQU $FF18
DEF rNR24 EQU $FF19
DEF rNR42 EQU $FF21
DEF rNR43 EQU $FF22
DEF rNR44 EQU $FF23
DEF rNR50 EQU $FF24
DEF rNR51 EQU $FF25
DEF rNR52 EQU $FF26

SECTION "Sound effect voices", WRAM0
; per voice: pointer to the next step (0 = idle), frames left, priority, duty, transpose
wSfx: ds 3 * 6
DEF SFX_PTR EQU 0
DEF SFX_TIMER EQU 2
DEF SFX_PRIORITY EQU 3
DEF SFX_DUTY EQU 4
DEF SFX_TRANSPOSE EQU 5

SECTION "Code: Sound effects", ROM0

SfxInit:
    ld a, $80               ; sound on
    ldh [rNR52], a
    ld a, $FF               ; every channel to both speakers
    ldh [rNR51], a
    ld a, $77               ; full volume
    ldh [rNR50], a
    ld hl, wSfx
    ld b, 3 * 6
    xor a
.clear:
    ld [hl+], a
    dec b
    jr nz, .clear
    ret

; Start effect A, transposed up hSfxTranspose semitones. Keeps BC, DE, HL.
PlaySfx:
    push hl
    push de
    push bc
    add a
    add LOW(SfxTable)
    ld l, a
    adc HIGH(SfxTable)
    sub l
    ld h, a
    ld a, [hl+]
    ld h, [hl]
    ld l, a                 ; HL = effect header
    ld a, [hl+]             ; voice
    ld b, a
    add a                   ; voice * 6
    add b
    add a
    add LOW(wSfx)
    ld e, a
    adc HIGH(wSfx)
    sub e
    ld d, a                 ; DE = voice slot
    ld a, [hl+]             ; priority
    ld c, a
    push hl
    ld hl, SFX_PTR + 1
    add hl, de
    ld a, [hl]              ; idle voices (pointer high byte 0) always take a new effect
    and a
    jr z, .take
    inc hl
    inc hl                  ; SFX_PRIORITY
    ld a, [hl]
    cp c
    jr z, .take
    jr c, .take
    pop hl
    jr .done                ; something more important is playing
.take:
    pop hl
    ld a, [hl+]             ; duty
    push af
    ld a, b                 ; pulse 1: set the sweep now
    and a
    ld a, [hl+]
    jr nz, .noSweep
    ldh [rNR10], a
.noSweep:
    ld a, l                 ; pointer to the first step
    ld [de], a
    inc de
    ld a, h
    ld [de], a
    inc de
    ld a, 1                 ; play the first step on the next update
    ld [de], a
    inc de
    ld a, c
    ld [de], a
    inc de
    pop af
    ld [de], a
    inc de
    ldh a, [hSfxTranspose]
    ld [de], a
.done:
    xor a
    ldh [hSfxTranspose], a
    pop bc
    pop de
    pop hl
    ret

SfxUpdate:
    ld hl, wSfx
    ld b, 0                 ; voice
.voice:
    ld a, [hl+]
    ld e, a
    ld a, [hl+]
    ld d, a                 ; DE = next step
    or e
    jr z, .next
    dec [hl]                ; frames left
    jr nz, .next
    ld a, [de]              ; step: frames (0 = the end), envelope, note / noise
    inc de
    and a
    jr z, .finish
    ld [hl], a
    push hl
    ld a, [de]
    inc de
    ld c, a                 ; C = envelope
    ld a, [de]
    inc de
    push af
    dec hl
    ld a, d                 ; store the pointer to the step after this one
    ld [hl-], a
    ld [hl], e
    pop af                  ; A = note / noise
    ld e, a
    inc hl
    inc hl
    inc hl
    inc hl                  ; SFX_DUTY
    ld a, [hl+]
    ld d, a                 ; D = duty
    ld a, b
    cp 2
    jr z, .noise
    ld a, e                 ; a pulse note: 0 is a rest
    and a
    jr z, .rest
    add [hl]                ; + transpose
    cp 63 + 1
    jr c, .inRange
    ld a, 63
.inRange:
    add a
    add LOW(SfxNotes)
    ld l, a
    adc HIGH(SfxNotes)
    sub l
    ld h, a
    ld a, [hl+]
    ld e, a                 ; E = period low
    ld a, [hl]
    or $80                  ; trigger
    ld h, a
    ld a, b
    and a
    jr nz, .pulse2
    ld a, d
    ldh [rNR11], a
    ld a, c
    ldh [rNR12], a
    ld a, e
    ldh [rNR13], a
    ld a, h
    ldh [rNR14], a
    jr .played
.pulse2:
    ld a, d
    ldh [rNR21], a
    ld a, c
    ldh [rNR22], a
    ld a, e
    ldh [rNR23], a
    ld a, h
    ldh [rNR24], a
    jr .played
.rest:
    ld c, 0                 ; silence: the envelope off
    ld a, b
    and a
    ld a, c
    jr nz, .restPulse2
    ldh [rNR12], a
    jr .played
.restPulse2:
    ldh [rNR22], a
    jr .played
.noise:
    ld a, c
    ldh [rNR42], a
    ld a, e
    ldh [rNR43], a
    ld a, $80
    ldh [rNR44], a
.played:
    pop hl
.next:
    ld a, l                 ; to the next voice slot (6 bytes each; HL is 2 in)
    add 4
    ld l, a
    adc h
    sub l
    ld h, a
    inc b
    ld a, b
    cp 3
    jp c, .voice
    ret
.finish:                    ; the effect ended: free the voice and fade it out
    dec hl
    dec hl
    xor a
    ld [hl+], a             ; pointer
    ld [hl+], a
    ld [hl+], a             ; timer
    ld [hl], a              ; priority
    dec hl
    ld a, b
    and a
    jr nz, .notPulse1
    xor a
    ldh [rNR12], a
    jr .next
.notPulse1:
    cp 1
    jr nz, .notPulse2
    xor a
    ldh [rNR22], a
    jr .next
.notPulse2:
    xor a
    ldh [rNR42], a
    jr .next

SECTION "Data: Sound effects", ROM0
SfxTable:
    dw Sfx_menu_move
    dw Sfx_menu_confirm
    dw Sfx_menu_back
    dw Sfx_option_change
    dw Sfx_press_start
    dw Sfx_move
    dw Sfx_move_held
    dw Sfx_rotate
    dw Sfx_land
    dw Sfx_clear
    dw Sfx_virus
    dw Sfx_win
    dw Sfx_lose
Sfx_menu_move:
    db 1, 1, 128, 0   ; voice, priority, duty, sweep
    db 2, $91, $35
    db 2, $51, $30
    db 0
Sfx_menu_confirm:
    db 0, 3, 64, 0   ; voice, priority, duty, sweep
    db 2, $C0, $31
    db 2, $C0, $35
    db 2, $C0, $38
    db 6, $C2, $3D
    db 0
Sfx_menu_back:
    db 0, 3, 128, 0   ; voice, priority, duty, sweep
    db 2, $A0, $2C
    db 5, $A2, $25
    db 0
Sfx_option_change:
    db 1, 1, 64, 0   ; voice, priority, duty, sweep
    db 2, $91, $2E
    db 2, $61, $35
    db 0
Sfx_press_start:
    db 0, 4, 128, 0   ; voice, priority, duty, sweep
    db 2, $D0, $25
    db 2, $D0, $29
    db 2, $D0, $2C
    db 2, $D0, $31
    db 2, $D0, $35
    db 2, $D0, $38
    db 10, $D3, $3D
    db 0
Sfx_move:
    db 1, 1, 0, 0   ; voice, priority, duty, sweep
    db 1, $61, $31
    db 1, $31, $31
    db 0
Sfx_move_held:
    db 1, 1, 0, 0   ; voice, priority, duty, sweep
    db 1, $51, $33
    db 1, $21, $33
    db 0
Sfx_rotate:
    db 1, 2, 0, 0   ; voice, priority, duty, sweep
    db 1, $90, $2C
    db 2, $91, $33
    db 0
Sfx_land:
    db 2, 2, 0, 0   ; voice, priority, duty, sweep
    db 4, $B1, $67
    db 0
Sfx_clear:
    db 0, 5, 128, 0   ; voice, priority, duty, sweep
    db 2, $C0, $31
    db 2, $C0, $35
    db 2, $C0, $38
    db 8, $C2, $3D
    db 0
Sfx_virus:
    db 2, 5, 0, 0   ; voice, priority, duty, sweep
    db 2, $D0, $14
    db 6, $A1, $24
    db 0
Sfx_win:
    db 0, 6, 128, 0   ; voice, priority, duty, sweep
    db 6, $C0, $25
    db 6, $C0, $29
    db 6, $C0, $2C
    db 6, $C0, $31
    db 6, $C0, $35
    db 24, $C4, $38
    db 0
Sfx_lose:
    db 0, 6, 128, 0   ; voice, priority, duty, sweep
    db 10, $B0, $2C
    db 10, $B0, $28
    db 10, $B0, $25
    db 30, $B5, $20
    db 0
SfxNotes:                   ; period for note index 1 (C2) upward; index 0 unused
    dw 0, 44, 157, 263, 363, 457, 547, 631, 711, 786, 856, 923, 986, 1046, 1102, 1155, 1205, 1253, 1297, 1339, 1379, 1417, 1452, 1486, 1517, 1547, 1575, 1602, 1627, 1650, 1673, 1694, 1714, 1732, 1750, 1767, 1783, 1798, 1812, 1825, 1837, 1849, 1860, 1871, 1881, 1890, 1899, 1907, 1915, 1923, 1930, 1936, 1943, 1949, 1954, 1959, 1964, 1969, 1974, 1978, 1982, 1985, 1989, 1992

SECTION "Data: Scene 0 tiles", ROM0, ALIGN[4]   ; DMA needs 16-byte alignment
Scene0Tiles:              ; "Title": 31 unique tiles
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $30, $F7, $38, $FF, $3C, $FD, $3E, $F3, $3F, $F7, $3B, $F7, $3B, $F7, $3B
    db $FF, $30, $F7, $38, $F7, $F8, $F7, $F8, $B7, $78, $77, $B8, $77, $B8, $77, $B8
    db $FF, $30, $F7, $38, $F7, $38, $F7, $38, $EF, $1C, $FD, $0E, $FB, $07, $FF, $03
    db $FF, $30, $F7, $38, $F7, $38, $F7, $38, $E7, $D8, $DF, $E0, $9F, $60, $7F, $80
    db $FF, $0F, $FF, $0F, $F8, $37, $F7, $38, $F7, $38, $F7, $38, $F7, $3B, $F7, $3B
    db $FF, $C0, $DF, $E0, $3F, $F0, $F7, $38, $E7, $18, $FF, $00, $FF, $F0, $F7, $F8
    db $FF, $0F, $FF, $0F, $F8, $37, $F7, $38, $F7, $38, $F7, $38, $FF, $3F, $FF, $3F
    db $FF, $C0, $DF, $E0, $3F, $F0, $F7, $38, $F7, $38, $F7, $38, $F7, $F8, $F7, $F8
    db $FF, $3F, $FF, $3F, $F0, $3F, $F7, $38, $F7, $38, $F7, $38, $FF, $3F, $FF, $3F
    db $FF, $F0, $F7, $F8, $07, $F8, $FF, $00, $FF, $00, $FF, $00, $FF, $C0, $DF, $E0
    db $F6, $39, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $E7, $18, $FF, $00
    db $77, $B8, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $E7, $18, $FF, $00
    db $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FE, $01, $FF, $00
    db $7F, $80, $7F, $80, $7F, $80, $7F, $80, $7F, $80, $7F, $80, $7F, $80, $FF, $00
    db $F6, $39, $F7, $38, $F7, $38, $F7, $38, $EF, $1F, $FF, $0F, $F8, $07, $FF, $00
    db $37, $F8, $F7, $38, $F7, $38, $F7, $38, $F7, $F8, $F7, $F8, $07, $F8, $FF, $00
    db $F0, $3F, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $E7, $18, $FF, $00
    db $37, $F8, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $F7, $38, $E7, $18, $FF, $00
    db $F0, $3F, $F7, $38, $F7, $38, $F7, $38, $FF, $3F, $FF, $3F, $E0, $1F, $FF, $00
    db $1F, $E0, $FF, $00, $FF, $00, $FF, $00, $FF, $F0, $F7, $F8, $07, $F8, $FF, $00
    db $FF, $3C, $FF, $40, $FF, $40, $FF, $38, $FF, $04, $FF, $04, $FF, $78, $FF, $00
    db $FF, $7C, $FF, $10, $FF, $10, $FF, $10, $FF, $10, $FF, $10, $FF, $10, $FF, $00
    db $FF, $38, $FF, $44, $FF, $44, $FF, $7C, $FF, $44, $FF, $44, $FF, $44, $FF, $00
    db $FF, $78, $FF, $44, $FF, $44, $FF, $78, $FF, $50, $FF, $48, $FF, $44, $FF, $00
    db $FF, $38, $FF, $44, $FF, $44, $FF, $44, $FF, $44, $FF, $44, $FF, $38, $FF, $00
    db $FF, $78, $FF, $44, $FF, $44, $FF, $78, $FF, $40, $FF, $40, $FF, $40, $FF, $00
    db $FF, $38, $FF, $10, $FF, $10, $FF, $10, $FF, $10, $FF, $10, $FF, $38, $FF, $00
    db $FF, $44, $FF, $44, $FF, $64, $FF, $54, $FF, $4C, $FF, $44, $FF, $44, $FF, $00
    db $FF, $FF, $FF, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF
    db $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF

SECTION "Data: Scene 0 maps", ROM0, ALIGN[4]    ; rows padded to 32 tiles so DMA can copy them whole
Scene0Map:
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $01, $02, $03, $04, $00, $00, $05, $06, $07, $08, $01, $02, $09, $0A, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $0B, $0C, $0D, $0E, $00, $00, $0F, $10, $11, $12, $0B, $0C, $13, $14, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $15, $16, $17, $18, $16, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $19, $1A, $16, $1B, $19, $1C, $15, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $1D, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $1E, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
Scene0Attr:               ; palette number per tile (Game Boy Color only)
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "Data: Scene 1 tiles", ROM0, ALIGN[4]   ; DMA needs 16-byte alignment
Scene1Tiles:              ; "Game": 22 unique tiles
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $0F, $FF, $0F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $33, $FF, $33
    db $FF, $C0, $FF, $C0, $FF, $30, $FF, $30, $FF, $00, $FF, $00, $FF, $F0, $FF, $F0
    db $FF, $0F, $FF, $0F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F
    db $FF, $C0, $FF, $C0, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $F0, $FF, $F0
    db $FF, $30, $FF, $30, $FF, $3C, $FF, $3C, $FF, $33, $FF, $33, $FF, $33, $FF, $33
    db $FF, $30, $FF, $30, $FF, $F0, $FF, $F0, $FF, $30, $FF, $30, $FF, $30, $FF, $30
    db $FF, $3F, $FF, $3F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F
    db $FF, $F0, $FF, $F0, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $C0, $FF, $C0
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $0F, $FF, $0F, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $F0, $FF, $F0, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F, $FF, $00, $FF, $00
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $F0, $FF, $F0, $FF, $00, $FF, $00
    db $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $04, $FF, $04, $FF, $04, $FF, $00
    db $FF, $87, $FF, $44, $FF, $44, $FF, $87, $FF, $05, $FF, $04, $FF, $04, $FF, $00
    db $FF, $87, $FF, $44, $FF, $44, $FF, $87, $FF, $04, $FF, $84, $FF, $47, $FF, $00
    db $FF, $C3, $FF, $04, $FF, $04, $FF, $83, $FF, $00, $FF, $00, $FF, $C7, $FF, $00
    db $FF, $C3, $FF, $04, $FF, $04, $FF, $83, $FF, $40, $FF, $40, $FF, $87, $FF, $00
    db $FF, $C0, $FF, $00, $FF, $00, $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $00
    db $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $00
    db $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $00

SECTION "Data: Scene 1 maps", ROM0, ALIGN[4]    ; rows padded to 32 tiles so DMA can copy them whole
Scene1Map:
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $01, $02, $03, $04, $05, $06, $07, $08, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $09, $0A, $0B, $0B, $0B, $0B, $0C, $0D, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $0E, $0F, $10, $11, $12, $13, $14, $15, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
Scene1Attr:               ; palette number per tile (Game Boy Color only)
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $01, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "Data: Scene 2 tiles", ROM0, ALIGN[4]   ; DMA needs 16-byte alignment
Scene2Tiles:              ; "Options": 29 unique tiles
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $0F, $FF, $0F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30
    db $FF, $C0, $FF, $C0, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30
    db $FF, $3F, $FF, $3F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3F, $FF, $3F
    db $FF, $C0, $FF, $C0, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $C0, $FF, $C0
    db $FF, $3F, $FF, $3F, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03
    db $FF, $F0, $FF, $F0, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $0F, $FF, $0F, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03
    db $FF, $C0, $FF, $C0, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $3C, $FF, $3C, $FF, $33, $FF, $33
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30
    db $FF, $0F, $FF, $0F, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $0F, $FF, $0F
    db $FF, $F0, $FF, $F0, $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $C0, $FF, $C0
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $0F, $FF, $0F, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $C0, $FF, $C0, $FF, $00, $FF, $00
    db $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $00, $FF, $00
    db $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $00, $FF, $00
    db $FF, $03, $FF, $03, $FF, $03, $FF, $03, $FF, $0F, $FF, $0F, $FF, $00, $FF, $00
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $C0, $FF, $C0, $FF, $00, $FF, $00
    db $FF, $F0, $FF, $F0, $FF, $30, $FF, $30, $FF, $30, $FF, $30, $FF, $00, $FF, $00
    db $FF, $00, $FF, $00, $FF, $00, $FF, $00, $FF, $3F, $FF, $3F, $FF, $00, $FF, $00
    db $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $04, $FF, $04, $FF, $04, $FF, $00
    db $FF, $87, $FF, $44, $FF, $44, $FF, $87, $FF, $05, $FF, $04, $FF, $04, $FF, $00
    db $FF, $87, $FF, $44, $FF, $44, $FF, $87, $FF, $04, $FF, $84, $FF, $47, $FF, $00
    db $FF, $C3, $FF, $04, $FF, $04, $FF, $83, $FF, $00, $FF, $00, $FF, $C7, $FF, $00
    db $FF, $C3, $FF, $04, $FF, $04, $FF, $83, $FF, $40, $FF, $40, $FF, $87, $FF, $00
    db $FF, $C0, $FF, $00, $FF, $00, $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $00
    db $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $04, $FF, $04, $FF, $07, $FF, $00
    db $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $40, $FF, $40, $FF, $80, $FF, $00

SECTION "Data: Scene 2 maps", ROM0, ALIGN[4]    ; rows padded to 32 tiles so DMA can copy them whole
Scene2Map:
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $01, $02, $03, $04, $05, $06, $07, $08, $01, $02, $09, $0A, $0B, $0C, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $0D, $0E, $0F, $00, $10, $00, $11, $12, $0D, $0E, $0F, $13, $14, $0E, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $15, $16, $17, $18, $19, $1A, $1B, $1C, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
Scene2Attr:               ; palette number per tile (Game Boy Color only)
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00
    db $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $02, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00, $00

SECTION "Variables", HRAM
hIsCGB: db
hScene: db
hVars:
hUpdateJump: ds 3        ; JP to the current update routine
hFrame: db
hPad: db
hPadNew: db
hTimer: db
hNextScene: db
hSfxTranspose: db       ; semitones up for the next PlaySfx
hFadeStep: db
hPalDirty: db
hCounter: db
hSel: db
hPadRepeat: db          ; pressed this frame, or held long enough to repeat
hRepeatTimer: db
hPatchJump: ds 3         ; JP to the pending map patch
hPatchSrc: dw
hPatchPending: db
hCursorY: db
hCursorX: db
hVarsEnd:
